### ISSUE TITLE
PixelClassification: Segmentation layer should not show anything on dirty slices

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#1033]
To reproduce:
1. Label and predict on one slice/timestep.
2. Turn on live prediction
3. Set segmentation layers to visible
4. Turn off live prediction
5. Go to a different slice/timestep => the segmentation is all green/red. This looks wrong, I would expect an empty image on those layers.

**Comment by stuarteberg** [comment]
The problem is that the segmentation layers are not produced with a cache: They are always computed on-demand using cached *input*.  When the cached input is zero across all channels, the output is undefined.

See [here](https://github.com/ilastik/ilastik/blob/f1fc32d75c523556816dd8a1de0b8d991a39695a/ilastik/applets/pixelClassification/opPixelClassification.py#L514)

Solution could be to have `OpMaxChannelIndicatorOperator` check for the special case of all-zero input, and output all-zeros in that case.
