### ISSUE TITLE
CSV/HDF5 Export should be found in the corresponding data-export-applet

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#1083]
Instead of adding a menu item in the object-classification or tracking applet, the csv- and hdf5-export options by @nielsbuwen should be provided in the corresponding data export applet for consistency reasons. Of course, this involves connecting the two applets through many additional slots, but this should be the way to go.

**Comment by martinsch** [comment]
Additionally, for the communication with knime, the export dialog should still be reachable from the object-classification and tracking applet.

**Comment by nielsbuwen** [comment]
Here is a screenshot of what it is currently looking like.
I added an export button to the "Object Prediction Export" applet and renamed the tab.

![inline-export](https://cloud.githubusercontent.com/assets/9267463/6849368/1a3844ae-d3d3-11e4-8b33-8f75273c7a47.png)

I didn't want to add a new entry for the ComboBox, because those exporters seem to work differently from the "KNIME"-exporter.

That button will open the same dialog as the "Export->Export Object Information" menu item.
The menu item also remains where it is.

If this is the way you meant it to be I will create a pull request for that.

**Comment by stuarteberg** [comment]
I think this UI is fine.  Can you rename the heading from "Export Features" to, I dunno, "Export Object Feature Table", or something similar?

Please go ahead and create a PR.  I'd like to take a look at the implementation.

@martinsch, How do you like this placement?

**Comment by martinsch** [comment]
That's better now, thanks.
