### ISSUE TITLE
use default colors for first two classes in pixel / object classification that will work for the most prevalent form of color blindness

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1114]
We have not had complaints on the mailing list; and yes, colors can be changed manually; but I have had repeated complaints during demos.

**Comment by FredHamprecht** [comment]
This will of course change the look and feel. Perhaps this should best be done when moving to version 1.2 or even 2.0

**Comment by burgerdev** [comment]
To illustrate the case, I did some simulations with [Color Oracle](http://colororacle.org/index.html) for our first ten colours. Labels are the horizontal strokes, going from label 1 (top) to label 10 (bottom). The images show experience simulations for [the most common types of colour blindness](https://en.wikipedia.org/wiki/Color_blindness#Background), Deuteranopia and Protanopia.

Seems like using blue/yellow (label 3/4) instead of red/green (label 1/2) would significantly improve accessibility. 

`LabelColors` is already a slot for `OpLabeling`, it should be possible to change label colours from a menu item (i.e. "activate colour-blind mode").

![deuteranopia](https://cloud.githubusercontent.com/assets/2814259/9080592/6b3b6f7c-3b55-11e5-923b-41871e47cb41.png)
![protanopia](https://cloud.githubusercontent.com/assets/2814259/9080593/6b443bfc-3b55-11e5-9a62-2aefe2ffb979.png)
