### ISSUE TITLE
Retaining label colours in simple segmentation export

### ISSUE THREAD

**Issue by amycharlotte** [ilastik/ilastik#1127]
I am attempting to export a simple segmentation from a pixel classification (in which there are 5 separate classes) to a file that can then be post-processed. When exporting to a tif or png without renormalization of pixel values the image appears black. When exporting to a tif or png WITH renormalizing (0-2 to 0-255) then four of the classes appear to be agglomerated into one foreground class (grey).

Is there a way to retain the label colours assigned during the classifier training in the export?
![0 5_simple segmentation](https://cloud.githubusercontent.com/assets/13210003/8536488/309f7c98-24a6-11e5-9679-6e4c12164bcd.png)
![0 5 - original image](https://cloud.githubusercontent.com/assets/13210003/8536494/477ec608-24a6-11e5-999f-af9b96138836.jpg)

**Comment by stuarteberg** [comment]
>When exporting to a tif or png without renormalization of pixel values the image appears black.

By default, the exported "Simple Segmentation" image will be a label-valued image, where each pixel has a value of 1,2,3,4, or 5, depending on the predicted label class.  In a plain image viewer, these pixels will all appear very dark (nearly black).  If you are able to adjust the contrast, you'll see the differences.

>When exporting to a tif or png WITH renormalizing (0-2 to 0-255) then four of the classes appear to be agglomerated into one foreground class (grey).

If you want to adjust the contrast in the file itself, you can use the "renormalize" option.  But the range on the left-hand side should reflect the range of the data, which in your case is 0-5, not 0-2.  Instead of pixel values of [1,2,3,4,5], your pixels will have values  [51,102, 153, 204, 255].

>Is there a way to retain the label colours assigned during the classifier training in the export?

In our next version, there will be a "what you see is what you get" button that allows you to export an image exactly as it appears in on your screen, including colors, transparency, etc.  If you are using Mac or Linux, you can try a beta version today:

http://files.ilastik.org/ilastik-master-Linux.tar.gz
http://files.ilastik.org/ilastik-master-OSX.zip

(Use the camera button in any 2D view.)

**Comment by amycharlotte** [comment]
All working now, the renormalization is where I was going wrong. Thank you for the help.

**Comment by stuarteberg** [comment]
Good to hear! Thanks for letting us know.
