### ISSUE TITLE
Our KNIME interface should use standard KNIME REST API

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik#1132]
The new version of KNIME (announced today) apparently has support for REST calls built in.  It may be an outgrowth of our own interactions with them, or it may be something new:

https://www.knime.org/blog/giving-the-knime-server-a-rest

Is that the same API we're using to communicate with KNIME? Or do we need to adapt?

cc/ @nielsbuwen

**Comment by nielsbuwen** [comment]
As far as I know this REST interface is not new. Someone already talked about it at a KNIME meeting several months ago. Perhaps it was under development then.

It seems to be a completely different API. I think they are using it to transfer data and not hilites.
But we don't need to adapt, because KNIME has so many interfaces for data reading/writing.
