### ISSUE TITLE
Conservation tracking and Animal Tracking do not use 2D convex hull and skeleton features

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik#1188]
These features were called via Select Features dialog but not via Subset Features used in these two workflows.

**Comment by JaimeIvanCervantes** [comment]
I stumble across this issue when I was trying to load my ilastik project file from Hytra, and I discovered that the classifier was trained using only the `Standard Object Features`. 

One of the problems occurs in `objectClassificationGui.py` where the `SelectedFeatures` slot is being modified straight from the GUI code. I'm working on a fix for this issue.

**Comment by stuarteberg** [comment]
To add some details: The correct features are only used iff you use the "subset features" window before training the classifier for the first time.  Once the classifier is trained, the features are cached and it is too late to change them.

The reason for this is that the GUI is (attempting to allow the user to provide "plugin" features in the "subset features" UI, instead of in the original "select features" UI in object extraction.  The only reason it accidentally works is that in [`handleSubsetFeaturesClicked()`](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/objectClassification/objectClassificationGui.py#L282), the feature dictionary from the object extraction applet is [retrieved](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/objectClassification/objectClassificationGui.py#L284), and [modified directly](https://github.com/ilastik/ilastik/blob/master/ilastik/applets/objectClassification/objectClassificationGui.py#L324), without going through the proper procedure of copying it and setting it on a slot, so that dirty state is propagated through object extraction.

Essentially `OpObjectExtraction` is not "aware" that it's `Features` slot contents have changed.

I think the proper solution should be:

1. By default, the ObjectExtraction `Features` slot should be populated with all available features (including plugins), even before the user has clicked the "Select Features" button.

2. In `ObjectClassificationGui`, don't modify the `computedFeatures` dictionary directly -- use a copy of it.

**Comment by akreshuk** [comment]
From what I recall, opObjectExtraction shouldn't be aware of what's happening in the object classification applet. The original idea was that you compute all possible features and experiment with different subsets in the classification applet. It looks like your proposed solution will actually bring it to this stage.
