### ISSUE TITLE
Tiff export stops working after switching between export formats

### ISSUE THREAD

**Issue by holgerhennig** [ilastik/ilastik#1203]
I'm using the pixel-based classifier in Ilastik 1.1.8.
Initially, tiff export of probabilities works fine. When switching to hdf5 export (or to png, bmp,...) and back to tiff export (without changing anything else) then it says in the image export options dialogue: "data type not supported by tiff" and the ok button is greyed out.

After saving and reopening the ilastik file (with export still set to tiff), then export to tiff works again (but stops working when switching between formats again).  

The same tiff export problem occurs with label and segmentation export.

**Comment by stuarteberg** [comment]
For some reason, our code excludes `float` from the list of acceptable pixel types.  A comment in the source code refers to some old [standards document](https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf), but as far as I can tell, it does allow float.  Plus, vigra seems to support float TIFFs just fine (both 32-bit and 64-bit).

Now fixed in master.
