### ISSUE TITLE
pop index out of range error in pixelclassification workflow

### ISSUE THREAD

**Issue by soledis92** [ilastik/ilastik#1244]
There is an issue with dropping the channel axis during prediction export in the pixelclassification applet.

How to replicate:
During prediction export if the axis order in the image export options is set from e.g. yxc to yx (dropping the channel) after closing the options menu saving the project leads to an "pop index out of range IndexError". If the project is closed in that condition it can't be opened again.

The only work around to save the labels was to manually add an empty channel axis to the hdf5 project file. After that the project can be opened again.

Image of the error:
![error](https://cloud.githubusercontent.com/assets/14301060/16579935/6bef2184-42a2-11e6-92ad-cc7439e722f8.png)

Cheers, Adrian

**Comment by snajder-r** [comment]
I can confirm the issue still persists in 1.3.2 rc1. Encountered this exact issue in the autocontext workflow when trying to save predictions as zyx instead of zyxc.

**Comment by k-dominik** [comment]
thx a lot for checking @snajder-r

**Comment by k-dominik** [comment]
can confirm this still is an issue

related (in a way): https://github.com/ilastik/volumina/pull/263

**Comment by i3v** [comment]
I just ran into this and this when trying to export a limited range of slices (15, not just one) from a 4D image (3D + 3 colors) with axis order conversion. And (it looks like) I was stupid enough to save the project after the error. As a result, my project file got damaged and the `pop index out of range` error was now preventing me from loading the project.

Thankfully, the fix was pretty easy. Just in case anyone would need this:
```python
import h5py
input = r'C:\project\project.ilp'
with h5py.File(input,  "a") as f:
    del f['Prediction Export']
```
The versions of the python packages I used:
```
python = "==3.7.9"
h5py = "==3.7.0"
```
Based on "C:\Program Files\ilastik-1.4.0.post1-gpu\conda-meta\").

Ilastik 1.4.0.post1.
