### ISSUE TITLE
Tracking with Learning workflow: disallow negative parameters in the solution

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1270]
or, more generally: add an l2-bias towards parameters that are sensible -- for example the parameters that we published in past papers. 

Bias should be strong when there are few annotations and vice versa.

**Comment by chaubold** [comment]
@ilastikdev: as an initial solution we could simply take the numbers that get out, check whether they are negative, and if not, set them to some small epsilon + warn that they are wrong. Or we fall back to the default parameters the Conservation Tracking workflow always used. @akreshuk said that she would like to have this check in the binary as soon as possible, because negative weights lead to tracking solutions that will just confuse the users.

**Comment by ilastikdev** [comment]
Default weights used to be
det 10
div 10
tra 10
app 500
disapp 500
normalized this translates to
.01
.01
.01
.7
.7
which is very far off from some typical weights from learning:
.92 
.11
.01
.27
.21
and
.77
.49
.01
.34
.19

So I would suggest:
.8
.4
.01
.3
.3
for the bias.

**Comment by ilastikdev** [comment]
Adding non-negativity constraints for the weights to the structured learning would be the best solution, 
but would require modifying opengm.

**Comment by ilastikdev** [comment]
Initial solution has been coded.

"... initial solution we could simply take the numbers that get out, check whether they are negative, and if not, set them to some small epsilon + warn that they are wrong."

**Comment by ilastikdev** [comment]
will open an issue in opengm:
"Learning needs a flag to trigger non-negativity constraints for weights" #472
