### ISSUE TITLE
Tracking with learning workflow: avoid funny weights by sanity check

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1271]
In the demo, we got out negative transition weights. Possible cause (?): not all cells in the crop were annotated. If indeed this is the reason, make sanity check (take user to un-annotated cells) or ignore these.

**Comment by ilastikdev** [comment]
Misunderstanding - when I said that there was not enough annotations I did not mean there were objects in the crop that were not annotated. What I meant is that the crop(s) were too small.

Check if everything in the crop(s) is annotated is already there - if not we get an error message that annotations violate the assumptions of the model.

**Comment by ilastikdev** [comment]
This issue is a subset of #1252.

**Comment by chaubold** [comment]
AFAIK Fred was referring to **my** presentation of structured learning at the workshop, where we got out negative numbers because I did not label some object that extended only for a few pixels into the crop. If you say this is a subset of #1252, then we should not only show the user how many objects are there left to label, but we should not even let him/her press the "Calculate Weights" button as long as the counter is not down to 0.

**Comment by ilastikdev** [comment]
Having forgotten one (or more) of the objects in a crop does not imply negative weights. Only the number of annotations for that particular weight.

The sanity check so far is if all annotated tracks are continuous, plus checks for mergers and single objects. So crop annotations can be incomplete and structured learning can still work providing there are enough annotations.

**Comment by ilastikdev** [comment]
For solutions to negative weights problem see #1270.
