### ISSUE TITLE
Automated feature selection should gracefully handle data sets that are too small for the largest filters in at least one dimension

### ISSUE THREAD

**Issue by FredHamprecht** [ilastik/ilastik#1280]
> When I first ran Ilastik, I loaded my images and selected all features.
> Then, Ilastik complained that the largest (sigma 10) features are too 
> big for my data. No problem with that, just deselected it.
> 
> But when I want to run the "suggest features", I get the very same 
> error message.

**Comment by k-dominik** [comment]
hint for whenever we tackle this, the root cause is in the following lines:

https://github.com/ilastik/ilastik/blob/c2621c9f28d8f005c39ab984d016dc27f8bd9c85/ilastik/applets/pixelClassification/FeatureSelectionDialog.py#L779-L782

This constructs the initial _all_ features matrix that is used to generate candidates in the automatic subset selection. To do this properly we need to expose the largest 3D sigma and use 2D features for the other ones.

Side note: Using 2D features on 3D data came later and has not taken into account into the feature selection process (this would be very interesting).
