### ISSUE TITLE
"Clear dividing" does not work

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1352]
It is not possible to remove a label in the object classification applets of the tracking workflow and clearing the labels also does not do what's expected. We should provide users a way to clear the labels while experimenting, without going through the dataset and unclicking everything.

**Comment by ilastikdev** [comment]
In tracking user can remove the largest merger label if not in LiveUpdateMode.
I will add a 'Delete All Labels Training' button,
but this would be usable and best done in ObjectClassfication.

Removing a label and not updating is an object classification problem.

**Comment by akreshuk** [comment]
I don't think we need a new button, the UI is already there. The context menu item for "clear label" should just work, whether in Object Classification or in Tracking.

**Comment by ilastikdev** [comment]
Prediction update is fixed when deleting a label (see 335ec2d) in object classification.

In tracking we removed the option to delete labels (Dividing/Not dividing) in the division classifier and
all but the last label in object classification because all these labels are needed.
At any time one can delete the largest merger label in non-interactive mode.

**Comment by akreshuk** [comment]
This is not exactly what I had in mind. I'm fine with not being able to delete a label. However, when you right-click, there is an option "clear label", which should keep the label there, but remove all annotations that were made in this color. This is the one not working at the moment. Sorry I wasn't clear in the beginning, but the fix you made is needed in any case, it seems.
