### ISSUE TITLE
extract2DConvexHullFeatures is not available in vigra version 1.11.0.post194

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [ilastik/ilastik#1426]
I created a fresh conda environment, and when I tried to run tracking, I got an error saying that `vigra.analysis` didn't have the `extract2DConvexHullFeatures` module available. I had to switch from vigra version `1.11.0.post194` to version `1.11.0.post196`and it worked. Here's the error log:

```python
...
  File "/groups/branson/home/cervantesj/miniconda3/envs/ilastik-cluster/ilastik-meta/ilastik/ilastik/plugins_default/vigra_objfeats_convex_hull.py", line 165, in _do_4d
    result = vigra.analysis.extract2DConvexHullFeatures(labels.squeeze().astype(numpy.uint32), ignoreLabel=0)
AttributeError: 'module' object has no attribute 'extract2DConvexHullFeatures'
```

**Comment by stuarteberg** [comment]
>I had to switch from vigra version 1.11.0.post194 to version 1.11.0.post196and it worked.

Right, the `.post194` version was built without `lemon`, so the convex hull features are unavailable.  The `.post196` version was built with `lemon`, so everything works.  Our `ilastik-versions` requirement list [correctly uses `.post196`](https://github.com/ilastik/ilastik-build-conda/blob/master/ilastik-versions/meta.yaml#L109).  No problems so far.

The issue is that that `ilastik-everything-no-solvers` package was out-of-date.  I've uploaded a new one now.
