### ISSUE TITLE
No access to raw data from project in headless

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1441]
If the classifier has been trained already, running the headless mode with such a project should not require access to the raw data anymore.

**Comment by stuarteberg** [comment]
**Background:**

The thing that makes this tricky is that the entire graph is connected and initialized when the project file is deserialized.  If the project has, say, 5 input files, then there are 5 slots feeding into the classifier training operator.  The classifier slot is therefore "not ready" unless all 5 of those slots are "ready" in turn.  But it doesn't make sense to declare a data input slot "ready" if we don't know anything about it (e.g. shape, axis order, dtype).

**Possible solution:**

Add a flag to the headless interface, `--dont-load-training-files` (or, ideally, something less awkward and more general).  When that flag is detected, the `DataSelection` applet won't deserialize *any* lanes into the workflow.  But the other applets, such as `FeatureSelection` and `PixelClassification`, will still deserialize their settings as usual, including the classifier cache.  I *think* deserialization and batch mode processing will still proceed normally, despite the fact that the workflow will have zero lanes.

Possible "gotchas": Some applets, such as thresholding store cached image data for each lane in the project file.  We have to make sure that the corresponding deserializers don't attempt to load those caches into the workflow operators -- there will be zero lanes, and therefore no caches in which they can inject the restored data.

**Comment by chaubold** [comment]
I might be totally wrong here, but if we run pixel classification in batch mode and have a trained random forest, then we should be able to simply ignore all parts of the graph that led to the Random Forest, meaning we could chop their connections when running in batch (probably already when setting up the workflow). That way the Random Forest serves as *input* to the graph and is ready because we can load it from the project. But I bet there's a good reason why this is not so easy, as always :smile:

**Comment by hno2** [comment]
This is fixed now, right?

**Comment by k-dominik** [comment]
true, thanks for the reminder!
