### ISSUE TITLE
Object Classification: classification seemingly random

### ISSUE THREAD

**Issue by barclaylee** [ilastik/ilastik#1566]
I am running the Object Classification workflow using segmented images from the Pixel Classification workflow. I've encountered a strange behavior that occurs when I am using the Brush tool to define some class labels. Repeatedly clicking on a previously labeled object keeps changing the class predictions for the other objects seemingly randomly. This seems strange because I should not be changing any of the class labels when I click on an already labeled object. Is this a normal behavior?

**Comment by akreshuk** [comment]
I can't reproduce this with one or 20 features selected. What I had seen before is that sometimes you label an unlabeled object with the same label the random forest predicted for it, and this changes the labels for other objects. It might seem counter-intuitive, but you have to remember the feature space is very multi-dimensional and even if you just confirm the classifier predictions, it can lead to a change in  your decision surface. 
Could you share your project with us? If you don't want to post it here, e-mail to team@ilastik.org.

**Comment by barclaylee** [comment]
I am seeing the labels for other objects change when I repeatedly click on an already labeled object. I've attached a sample file for you to take a look at, the t=0 image is already labeled for the cells I'm interested in. It is a very noisy image though (phase-contrast) so that might have something to do with it.


[073117_sample.ilp.zip](https://github.com/ilastik/ilastik/files/1188235/073117_sample.ilp.zip)

**Comment by akreshuk** [comment]
Hey there, sorry for the late reply, summer vacations and all.

I looked at your project file and I see the same effect. In this case you are really observing the randomness of the random forest. First of all, you have a lot of features, with the histograms it gets up to 173 features for only 10 labels. The out-of-bag error is at 0.2, which is very big. I'd recommend adding a lot more labels. If you add at least 50 and it doesn't stabilize, let's rethink the feature selection, but try labeling more first. If you start ilastik in debug mode (pass --debug flag if you start from the command line on Linux or Mac, not sure about Windows), the out-of-bag error will be printed in the command line. Otherwise, it's always printed into the ilastik log file, called ilastik_log.txt, located in your home directory. Watch for it decreasing as you click more objects.

**Comment by k-dominik** [comment]
@akreshuk can this be closed?

**Comment by akreshuk** [comment]
Let's close and if @barclaylee has more questions we'll re-open.
