### ISSUE TITLE
File paths containing Korean characters do not work

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik#1663]
A Korean user just experienced problems on windows with the 1.3.0b3 binary when saving or loading files from paths that contain Korean characters. Our string handling should be fully unicode now, but maybe there's something off with the file path handling?

This could also affect other operating systems.

**Comment by chaubold** [comment]
(Works fine on macos with German Umlauts)

**Comment by stuarteberg** [comment]
Perhaps the user's machine returns different values for [`sys.getdefaultencoding()`][1] and [`sys.getfilesystemencoding()`][2]?  I don't know if we're very careful about calling the correct function for each situation.

[1]: https://docs.python.org/3.6/library/sys.html#sys.getdefaultencoding
[2]: https://docs.python.org/3.6/library/sys.html#sys.getfilesystemencoding

**Comment by chaubold** [comment]
We just had a German user complain about the same thing, on Windows, with an "ü" in the path. So this seems to be urgent.

**Comment by chaubold** [comment]
@stuarteberg your hint was good, I was able to solve it by setting the [`PYTHONLEGACYWINDOWSFSENCODING`](https://docs.python.org/3.6/using/cmdline.html#envvar-PYTHONLEGACYWINDOWSFSENCODING) environment variable. I tried using the python calls to set this variable as well which for some reason didn't work. So I'm thinking of putting it into the [exe](https://github.com/ilastik/ilastik-build-conda/blob/master/windows-installer/ilastik-exe/ilastik_launch/ilastik_launch.cxx) and the `run_ilastik.bat`.

**Comment by stuarteberg** [comment]
Jeez, what a pain.  Nice find.

**Comment by FynnBe** [comment]
even setting the environment variable did not solve the problem for me.
I haven't tried all combinations yet, only started with korean symbols in the project file name. This is important, because maybe the pythonlecacy... variable only solves unicode symbols in file paths, but not file names, because:
There is an isssue in h5py < 2.7.1 with unicode characters, for which there is already a workaround/fix in h5py 2.7.1: https://github.com/h5py/h5py/pull/841/files 
We are currently using h5py 2.7.0

**Comment by FynnBe** [comment]
that workaround in h5py 2.7.1 turned out to be not sufficient. It is rather a preparing step to fix it in the future as hdf5 itself can't properly deal with unicode yet. To allow for unicode characters in the path nonetheless I propose to change directory to whereever (h5) files have to be opened. I was able to open a project in that manner already. import/export of data should work in the same manner

**Comment by akreshuk** [comment]
Don't forget the Temp directory problem: we save the temp file with the classifier there when saving classification projects and if there are unicode characters in the path, it doesn't work

**Comment by chaubold** [comment]
The fix that I had above doesn't apply to the _easy_ special chars like German umlauts, because they are contained in the LATIN encoding Windows uses...

To fully fix that, we've experimented with quite a number of options now. Even if the strings get handled properly in Python, `hdf5` refuses to open files that have unicode characters inside the file name (not the path!). There seems to be a simple fix to that, which @FynnBe is trying out now: https://github.com/conda-forge/hdf5-feedstock/issues/47. Unfortunately that means we have to build our own version of `hdf5` and rebuild everything that depends on it.

Still, this only affects Windows!

**Comment by akreshuk** [comment]
The work around of @FynnBe seems to be working, we heard it even runs on fully Chinese Windows now.
