### ISSUE TITLE
Supply stacking axis via command line

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1678]
Running ilastik in headless mode on image stacks (`"my_image*.somefiletype"`) will automatically stack them across `z`. We should expose the stacking axis as a paramter via the command line.

in the code snipped below, in line 103, the stacking axis is set to default because `self.SequenceAxis.ready()` is `False`.

https://github.com/ilastik/lazyflow/blob/71910c15bc78225f0210d207a064beb9cce180c0/lazyflow/operators/ioOperators/ioOperators.py#L99-L103

make also sure that it works with the h5-type stack readers `opStreamingHdf5SequenceReaderM` and `opStreamingHdf5SequenceReaderS`

**Comment by jbychang** [comment]
I suspect that I’ve been having problems related to this because I am trying to stack across channels, and not z, in headless mode.

As a temporary fix, could someone share a sample script that uses the python interpreter to track images using a pre-trained tracking project? Something like the script available at  

https://github.com/ilastik/ilastik/blob/master/examples/example_python_client.py 

It seems like it would be straightforward for me (and if there are others with similar issues) to just modify that script to point to the data in the appropriate way.

Best,
Jeremy

**Comment by ilastikdev** [comment]
Hi Jeremy,

Can you please send us a small version of your dataset (or a download link)
and we will see what are the possible solutions.

Sincerely,

Janez.





Quoting jbychang <notifications@github.com>:

**Comment by jbychang** [comment]
Hi Janez et al.,

Thanks for the note. Yes, please find two "tyx" .h5 files at the following two links:

https://www.dropbox.com/s/4gzchxep4hiuwsr/WellC05_Seq0010_c1____________Input.h5?dl=0
https://www.dropbox.com/s/yze83kpf4w4qmze/WellC05_Seq0010_c2____________Input.h5?dl=0

In order to train the pixel classifier (and the tracking algorithm), I used the "Input Data" applet to stack these across channel. I'd now like to use this classifier on my images in other wells, but I can't tell Ilastik to stack across channel in headless mode.

One possible solution is to make a single "tyxc" .h5 file. However, because I'd like to train other classifiers using different groups of channels (I have a total of 5 channels, and I have a separate classifier that uses channels 1, 2, and 5), I would have to make .h5 files containing many of the same images for each classifier. This is a problem for my full dataset, for which each image is 10 mb, and I have tens of thousands per experiment (the links above contain downsampled images).

Thanks,
Jeremy

**Comment by FynnBe** [comment]
When pull request https://github.com/ilastik/ilastik/pull/1685 is merged (and new binaries released) you will be able to stack along any (t, z or c) axis in headless as well, using the --stack_along=c argument.

**Comment by jbychang** [comment]
That's great. Thank you!

**Comment by k-dominik** [comment]
#1685 is merged, so we can consider this resolved :)
