### ISSUE TITLE
New Feature: Export labels done by the pixel classification labeler

### ISSUE THREAD

**Issue by Nitaym** [ilastik/ilastik#1684]
Hello,

In order to do more tests in more ML tools, we need to export the scribbles done in ilastik as a picture.

I couldn't find a way to do it so I've started adding it myself, see here:
https://github.com/Nitaym/ilastik/commit/6f2171c25b78fdb335932d92e60be8e04d5c30fc

However - I cannot find a way to get the name of the file currently being labelled. Where could I find it?

Is this something the authors intend to add? Should I create a PR?

**Comment by stuarteberg** [comment]
>I couldn't find a way to do it so I've started adding it myself

Whoa, nice!  Very resourceful of you to implement your own solution.

>Is this something the authors intend to add?

As it turns out, this feature already exists.  There are two different ways to do it:

- Right-click on the "Labels" list item in the layer list (lower left-hand corner of the screen), and select the "Export...".  (See: http://ilastik.org/documentation/basics/layers)

OR

- On the "Prediction Export" page, use the dropdown menu to change the export "Source" to "Labels". (See: http://ilastik.org/documentation/basics/export)

**Please Note:** Both of the above methods will give you a label image, i.e. an image where most pixels are 0, but your brushstroke pixels have value 1, 2, 3, etc. (depending on how many label classes you have).  If you open the image in a standard viewer, the entire image will appear dark, since pixel values of 1 and 2 are quite dark and nearly indistinguishable from 0 pixels.

**Comment by Nitaym** [comment]
Thanks!

Is there a way to export using "Prediction Export" without turning on "Live
Update"?

Thanks
Nitay

**Comment by stuarteberg** [comment]
The [headless mode][1] is the only option, I think.

[1]: http://ilastik.org/documentation/basics/headless

**Comment by stuarteberg** [comment]
Wait, no, sorry, I think "Prediction Export" automatically gives you the correct results, as if you had clicked "live update".  Are you seeing something that makes you think that's not right?

**Comment by Nitaym** [comment]
Well, I might be doing something wrong, but "Prediction Export" is grayed out until I enable "Live Update". Is there a way to get to prediction export (only of the labels) without the live update?

**Comment by stuarteberg** [comment]
Ah, I see.  No, the "Prediction Export" page is not available until you have trained a classifier.  (You don't intend to use the classifier, but the rule stands nonetheless.)

If you don't want to train a classifier, then your only option is to use the right-click menu as described above.

**Comment by akreshuk** [comment]
It's somewhat related to people wanting to export object features without object classification. I think we should just enable all applets and make the checks later on.
