### ISSUE TITLE
Is it able to import a probability map created using the pixel classification for carving?

### ISSUE THREAD

**Issue by hanginzer** [ilastik/ilastik#1781]
I want to do the batch processing for carving. So I would like to import a probability map created using the pixel classification. Is it possible?

**Comment by akreshuk** [comment]
Carving is not really suitable for batch processing - it requires a user to place a seed inside and outside each object at least once. Could you possibly mean the multicut workflow? Then yes, you can import the pixel classification maps. We recommend exporting them as uint8 (rather than the float default) to save space.

**Comment by hanginzer** [comment]
Thank you so much for you response. I understood.
