### ISSUE TITLE
In multicut, you need to click Live Predict twice more if you clicked it too early

### ISSUE THREAD

**Issue by snajder-r** [ilastik/ilastik#1858]
In the Training and Multicut part, if you already have "Live Predict" selected and switch the Current View to a different lane, **or** if you switch the current view and then quickly click "Live Predict", the "Live Predict" button will remain toggled, but live prediction is actually still turned off. 

You then have to deactivate and re-activate live prediction button in order for it to actually be activated.

Expected behavior: if the Live Predict button is toggled on, live prediction should really be on.

**Comment by paulhfu** [comment]
This only happens when changing lanes for the first time. After that, the "Live Predict"  button adopts the state that it was last in, in respective lane. Other workflows like Pixel Classification don't differentiate in the states of "Live Predict" in different lanes. I guess this is also the expected behavior in Multicut. Which is, "Live Predict" it is only toggled when clicked.
