### ISSUE TITLE
RandomForest(): Feature matrix contains NaNs

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik#2000]
https://gist.github.com/tischi/30c54a879ae7397480431e6fdfa2bf1e

**Comment by k-dominik** [comment]
Hey @tischi,

I see you are using ilastik `1.3.0` (which is 2 years old...). Have you, by any chance, saved this project? Would be a nice idea to try it with one of our later ones (why not `1.3.2`, which is the current stable one). I remember there were some problems in our fastfilters package, maybe it's related to that and already resolved. Otherwise it would be very interesting to get this project :)

**Comment by tischi** [comment]
oops, did not realise!
we will try again with the new version!
