### ISSUE TITLE
OSX binary 1.3.3post1 can not be run

### ISSUE THREAD

**Issue by elmbeech** [ilastik/ilastik#2155]
## Describe the bug

OSX 1.3.3post1 binary can not be run.

+ In my "Security & Privacy" "System Preferences" I allow apps downloaded from "Anywhere" to be run. So this should not be the issue. 
+ I run MacOS 10.13.6 (High Sierra) which is > 10.9 (the minimum requirements). So this should not be the issue either. 

## To Reproduce

1. I downloaded the latest OSX binary (1.3.3post1) from https://www.ilastik.org/download.html
2. When I double-click it I get the error that "the app can't be opened because the identity of the developer cannot be confirmed".
3. Digging a bit deeper, it looks like the downloaded code does not match the original signed code.

I downloaded twice, and the error occurred both times. 

## Error message/traceback 

See png files attached. 

<img width="420" alt="ilastik1 3 3 1_osx10 13" src="https://user-images.githubusercontent.com/154283/68060927-ae9d2c80-fcbf-11e9-9163-c99f573cd5ad.png">

<img width="391" alt="illastik1 3 3 1_osx10 13_machelp" src="https://user-images.githubusercontent.com/154283/68060932-b1981d00-fcbf-11e9-83d3-87a6719f060c.png">

## Desktop (please complete the following information):
 - ilastik version: 1.3.3post1 binary
 - OS: macOS 10.13.6

**Comment by elmbeech** [comment]
With this instruction is possible to open the app:

<img width="463" alt="20191104_illastik_howtorun" src="https://user-images.githubusercontent.com/154283/68177838-6e97ad00-ff3e-11e9-8071-8e4a18a77d85.png">

I will close this issue. Elmar

**Comment by k-dominik** [comment]
Hi @elmbeech,

sorry for not replying. Most of the ilastik team was traveling last week.  Thank you very much for putting in the time to find a solution to this problem. We will add a note about this in our docs!

Cheers
Dominik

**Comment by elmbeech** [comment]
Hi Dominik, 

I am happy to server with this little. 
Thank you for writing such a cool software.

Best, Elmar


 ---- On Tue, 05 Nov 2019 05:44:06 -0800 Dominik Kutra <notifications@github.com> wrote ----

**Comment by GMaciag** [comment]
Hi @k-dominik 

I would like to say that the solution provided by @elmbeech is not working. 

I have tried today to install the ilastik software `version 1.3.3post3 (2020-05-03)` on mac and got the same error as first posted by @elmbeech. My SIP is disabled. I can install literally any other software from unidentified developers, just not ilastik.  After following the proposed "solution", I'm still getting the following error message:
![Image 28-07-2020 at 10 40 (1)](https://user-images.githubusercontent.com/31366577/88641579-b5769580-d0bf-11ea-83c5-cc16f3a82144.jpg)
Looking into Apple's Support page here's what they write:
![Screenshot 2020-07-28 at 10 47 44](https://user-images.githubusercontent.com/31366577/88641988-303fb080-d0c0-11ea-8041-dbefefaaa4b3.png)

Can you please reopen the issue and look into it? Seems the app is impossible to install on macOS, due to being detected as malware (not just that it is from unidentified developer). Apple just recommends to "look for an alternative app". 

I have tested on macOS Mojave 10.14.6 and Catalina 10.15.5, both with the same result.

**Comment by GMaciag** [comment]
Alright, I found a solution that works for now. In Terminal execute:
```
xattr -d com.apple.quarantine /Applications/ilastik-1.3.3post3-OSX.app/
```

This disables Apple's alerts for that particular app permanently and I am able to open and run it. 

I still think you should look more into that issue. It doesn't seem right you're distributing software that acts as a malware to the point where I need to hack the security settings on my laptop to open it.

**Comment by elmbeech** [comment]
I think it is apple who causes the problem, not ilastk. There OS gets more and more worse with every release. I said good by to apple. OS high sierra was the last that I was running.Install pop os! It is real alternative and it is free as in freedom. https://pop.system76.com/Best, Elmar ---- On Tue, 28 Jul 2020 02:52:21 -0700  notifications@github.com  wrote ----
Alright, I found a solution that works for now. In Terminal execute:
xattr -d com.apple.quarantine /Applications/ilastik-1.3.3post3-OSX.app/

This disables Apple's alerts for that particular app permanently and I am able to open and run it.
I still think you should look more into that issue. It doesn't seem right you're distributing software that acts as a malware to the point where I need to hack the security settings on my laptop to open it.

**Comment by GMaciag** [comment]
Hi @elmbeech 

Thank you for the recommendation, I appreciate it. MacOS is a standard issue at my university, not much we can do about it. I was actually helping with the issue for a colleague and installing a different OS would not be a viable solution ;) 

But I understand the struggle of trying to adjust to Apple's whims.
