### ISSUE TITLE
Autocontext, second round display problems with float images

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2174]
## Describe the bug
When using a `float32` image as input, it will be displayed in black in the second round.

## Expected behavior
Image should be displayed properly (as in first round, too)

## To Reproduce

you can produce some data:

```python
import numpy
data = numpy.random.random((100, 200))
numpy.save("testdata.npy", data)
```

Within the autocontext workflow
1. add the testdata
2. select some features
3. add some annotations (random)
4. go to the next feature selection applet - here the image will be all black.

## Desktop (please complete the following information):
 - ilastik version: 1.3.3pos2
 - OS: Ubuntu 18.04

**Comment by sdamrich** [comment]
I also experienced this issue with
ilastik version: 1.3.3.post3
OS: Ubuntu 18.04
and with `.tif` images whose data type was decoded to `UINT16`, giving the warming
`Warning: TIFFDecoder: no TIFFTAG_SAMPLEFORMAT or TIFFTAG_DATATYPE, guessing pixeltype 'UINT16'`

The issue seems to be fixed in ilastik version 1.4.0b15.
