### ISSUE TITLE
Running ilastik on a linux server

### ISSUE THREAD

**Issue by toshashah** [ilastik/ilastik#2177]
when I run ./run_ilastik.sh on Linux server I get this error
```
Warning: Ignoring your non-empty LD_LIBRARY_PATH
Warning: Ignoring your non-empty QT_PLUGIN_PATH
Could not find PATH/ilastik-1.3.3post2-Linux/python-scripts/ilastik-install. ignoring.
Starting ilastik from PATH/Ilastik/ilastik-1.3.3post2-Linux".
QXcbConnection: Could not connect to display
Fatal Python error: Aborted
```

_Edit: removed boilerplate_

**Comment by k-dominik** [comment]
Hi @toshashah,

I'm not sure what's happening, but since you mention that it is a linux server, it might be missing some GUI related packages. There is a similar discussion on forum.image.sc where [the solution](https://forum.image.sc/t/running-ilastik-gui-from-a-container/33477/2?u=k-dominik) involved adding several missing packages:

* libglu1-mesa-dev
* qt5-default
* libgl1-mesa-glx

maybe this is the case for you, too?

**Comment by k-dominik** [comment]
Hi @toshashah, did you have time to try this? Did it resolve your problem?

**Comment by jjerphan** [comment]
As Ilastik is launching with its GUI by default, if  connected to the server via an SSH session without X11 Forwarding, Ilastik will fail trying to find the display to use for the GUI because there's any by default.
