### ISSUE TITLE
Getting mask from ilastik pixel classifier

### ISSUE THREAD

**Issue by asmagen** [ilastik/ilastik#2215]
I have defined the pixel classifier for a couple of histology images and applied the following strategy to run it on new images via command line to allow batch execution:
./ilastik-1.3.2-OSX.app/Contents/ilastik-release/run_ilastik.sh  --headless --project=MyProject.ilp my_next_image1.png my_next_image2.png
However the output is an h5 file called probabilities. I wanted to get a mask per image because I just want to count the density of positive pixels per FOV.
Using --output_format=tiff gives me an image which doesn't seem to have much to do with the classifier I built. Using --export_source="Simple Segmentation" gives only a black image.
Why do you think the segmentation output is empty while the segmentation in the application GUI worked? And most importantly, how can I get such mask annotating only the positive pixels?
Thanks
<img width="1676" alt="Screen Shot 2020-03-24 at 11 23 26 AM" src="https://user-images.githubusercontent.com/11299568/77444129-e8cbaf80-6dc1-11ea-87be-e76ab06964a0.png">

**Comment by k-dominik** [comment]
Hi @asmagen,

first of all I think you're almost there! To start off with, [here are the headless mode docs](https://www.ilastik.org/documentation/basics/headless). 

> However the output is an h5 file called probabilities. I wanted to get a mask per image because I just want to count the density of positive pixels per FOV.

ilastik let's you specify your output data format and name, along with various other settings. Which format are you striving for?

As for the output-file per image, please consider using placeholder (magic values) in your `--output_filename_format` command line parameter.

Something like the following should work:

```bash
./ilastik-1.3.2-OSX.app/Contents/ilastik-release/run_ilastik.sh \
    --headless --project=MyProject.ilp \
    --output_format=png \
    --output_filename_format="/path/to/results/{nickname}_segmentation.png" \
    --export_source="Simple Segmentation" \
    my_next_image1.png my_next_image2.png
```

there you'd get a new file, based on the on the original filename. E.g. `/parh/to/results/my_next_image1_segmentation.png` ... Of course you'd have to find a sensible value for `/path/to/results`...

> Using --output_format=tiff gives me an image which doesn't seem to have much to do with the classifier I built. Using --export_source="Simple Segmentation" gives only a black image.

so the "probabilities" output will produce a multi-channel image (one channel per Label Class) where pixel values range from `0.0` to `1.0`. The "Simple Segmentation" output goes through every pixel, looks at which label has the highest probability and sets the Label Class index as a value in a single channel unsigned integer image (so values are, `0`, `1`, `2`, `3` ...). When you open, this image might appear black because the contrast is very very low. When you look at it in Fiji, you can apply the Glasbey lookup table to get a different visual representation of the same image ([point 4 in our faq](https://www.ilastik.org/documentation/basics/common_problems#4-my-exported-results-are-all-black).

> How can I get such mask annotating only the positive pixels?

I think you already have them! Just try applying the lookup table. If you then want to count, you'll have to count each pixel that has the value of the Label Class you are interested in. The mask with the pixels your are interested in you would get accordingly by thresholding for this numerical value.

**Comment by asmagen** [comment]
Thanks for the input. How do I know the channel order (matching to class label)? And when I load the result png and binarize the image to be a mask of all the pixels matching a particular class, how do I apply the mask? The conventional approach I use doesn't work here:
```
>>> positive_pixels_dir = '/Users/Assaf/Dropbox/shared_imaging/positive_pixels/CD3/'
>>> pixel_classification = cv.imread(positive_pixels_dir+"Li63T_segmentation.png")
>>> pixel_classification.shape
(1723, 1171, 3)
>>> mask = pixel_classification==1
>>> tile_image = cv.imread(tile_dir+'/tile_5_6.png')
>>> res = cv.bitwise_and(tile_image,tile_image,mask=mask)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected Ptr<cv::UMat> for argument 'mask'
```

**Comment by asmagen** [comment]
@k-dominik any idea regarding my question?

**Comment by k-dominik** [comment]
Hi @asmagen,,

first of all are you sure you have exported the correct source from ilastik? I see the image has 3 channels. The simple segmentation has a single channel only.
The values of this image will follow the sequence of labels in the training applet.
So all pixels that belong to Label1 have the pixel value 1
All pixels that belong to Label 2 have the pixel value 2 ... and so on
So before you go any further, try to confirm that you are using the correct output. And confirm in every step, that all the images you create (e.g. `mask`) have the shape you expect.

**Comment by asmagen** [comment]
Hi @k-dominik,
It is the right matrix, it just that it has 3 channels with the same information (1 or 2 value) for some reason. I got the following to work where I discretize the 1 or 2 classification to a binary then gray scale and then apply the mask to generate the attached picture. But I think it's a very convoluted way to do it and they must be a more straight forward way. Can you advise please?
<img width="488" alt="Screen Shot 2020-03-26 at 2 44 45 PM" src="https://user-images.githubusercontent.com/11299568/77684721-b7ddad00-6f70-11ea-9854-115c6daf4559.png">

```
>>> classification = cv.imread(output_filename)
>>> classification.shape
(11710, 17230, 3)
>>> mask = classification
>>> mask[mask == 1] = 255
>>> mask[mask == 2] = 0
>>> img2gray = cv.cvtColor(classification,cv.COLOR_BGR2GRAY)
>>> ret, mask = cv.threshold(img2gray, 100, 255, cv.THRESH_BINARY)
>>> mask_inv = cv.bitwise_not(mask)
>>> positive_pixels = cv.bitwise_and(cropped,cropped,mask=mask)
```

Thanks!

**Comment by k-dominik** [comment]
Hi @asmagen,

in general: are you set on using OpenCV? scikit-image is a nice alternative and has a more pythonic api in my opinion. Furthermore I could actually help you with scikit-image without googling. So for your OpenCV stuff:

`cv.imread` [docs](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_image_display/py_image_display.html#using-opencv): seems like you have to pass a flag to this function in order to load the data as grayscale. So you should `cv.imread(output_filename, 0). `classification` will only have a single channel then. 


In your current code, all three channels of this image have the same information. If you say `mask = classification`, you only copy the reference; This means that both variables point to the same data. Whatever you change in the first, you change in the second as well.

`img2gray` is only needed because your mask has 3 chanels. So it will not be needed once loaded as gray value. `mask = classification[..., 0]` would **copy** only the first channel of your classification image, you could manipulate it all you want and would have a proper mask. If you drop the "= 255" stuff, mask will also be a boolean image and can be easily inverted (using plain numpy). E.g. `numpy.logical_not`... But this is also not necessary, since you could use `cv.bitwise_and` insted with the non-inverted mask...

Aaanyway. In scikit-image this would look like the following, assuming simple segentation output (not tested):

```python
import skimage
import skimage.io

raw_filename = "some_original_image.png"
output_filename = "some_file.png"

raw_image = skimage.io.imread(raw_filename) 
segmentation_image = skimage.io.imread(output_filename)

# no clue about the cropping image you do but for the sake of the example
# exclude border of 100 pixels
cropped_raw_data = raw_image[100:-100, 100:-100]
cropped_segmentation = segmentation_image[100:-100, 100:-100]

# get the mask of the first class, all pixels that belong the that class are True in that image
mask = cropped_segmentation == 1

positive_pixels = cropped_raw_data * mask
```





```

**Comment by asmagen** [comment]
Thank you
