### ISSUE TITLE
Problem with exporting tracking results

### ISSUE THREAD

**Issue by LouisC-H** [ilastik/ilastik#2240]
## Describe the bug
Hi. When using Ilastik, I'm able to generate high-quality tracking data using the tracking modules, but then when exporting it seems to sometimes get all jumbled up again (Note: doesn't always happen. On some image-sets, it's fine)

## Expected behavior
The tracking results shown in the "tracking- structured learning" tab should then carry over to the "tracking- results export" tab

## To Reproduce
Not sure honestly. It only sometimes happens

## Screenshots
If applicable, please add screenshots to help explain your problem.

I captured video footage which I hope shows the problem. 
https://www.dropbox.com/s/sz261c6eed1dhtz/ilastik_tracking_bug.mp4?dl=0

## Desktop (please complete the following information):
 - ilastik version: 1.3.2
 - OS: Windows 10

**Comment by k-dominik** [comment]
Hi @LouisC-H,

Thank you for the report! And the video really helped, because it was a problem I already forgot about!
In ilastik 1.3.2 the outputs in Tracking with Learning were wired erroneously. So what you get as a preview when you select "Tracking-Result" is in fact the Object Identities Layer. The next stable version of ilastik (1.3.3post2) includes this fix  (for reference bdd9088a2943c28f0ba9de4d14b736fa9b503ae5).
Is there a particular reason holding you back from updating ilastik?

Cheers
Dominik

**Comment by LouisC-H** [comment]
Thanks for the reply, that's good to know. There's no particular reason that I haven't updated it yet, I just didn't think to check for updates. Thanks for the help
