### ISSUE TITLE
Error in Multicut batch processing: log_exception 15692 10148 Error encountered during batch processing: wrapped C/C++ object of type AddFileButton has been deleted

### ISSUE THREAD

**Issue by SeforaC** [ilastik/ilastik#2250]
## Describe the bug
Error in Multicut batch processing: log_exception 15692 10148 Error encountered during batch processing: wrapped C/C++ object of type AddFileButton has been deleted

## Expected behavior
I am using the Multicut Boundary based Segmentation workflow to segment F-actin 3D stacks. After training the classifier, I tried to use the batch processing option to segment the rest of the stacks. But after chossing both the raw data and the probability maps, I get the followinf error: log_exception 15692 10148 Error encountered during batch processing:
wrapped C/C++ object of type AddFileButton has been deleted
![Batch processing error](https://user-images.githubusercontent.com/65655169/82433423-b375d200-9a91-11ea-968a-086d8cb70c77.png)

## To Reproduce
Within the Boundary-based Segmentation with Multicut workflow
1. Add 3d data in the data selection applet
2. Go to DT watershed applet, after selecting the desired settings Click on 'Update Watershed'
3. Go to Training and Multicut, applet, train the classifier
4. After obtaining the desired results, data export
5. Batch processing: I load the data. 

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2020-05-20 11:45:54,466 log_exception 15692 10148 Error encountered during batch processing:
wrapped C/C++ object of type AddFileButton has been deleted

```

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.3post3]
 - OS: [Windows 7]

**Comment by jerolon** [comment]
Hi, I don´t know if this applies to you, but I was getting the exact same error while running batch multicut boundary segmentation; though I was running it on a series of 2d images. I noticed that even though the error appears, it always processed correctly the first image of the series, as the result appeared on the output folder.

I had a series of 1000 tif images stored in C:\pathtorawdata\
originalimageseries_0000.tif
originalimageseries_0001.tif
....
originalimageseries_0999.tif

And a series of probability maps stored in C:\pathtoprobabilities\
originalimageseries_0000_Probabilities Stage 2.h5
originalimageseries_0001_Probabilities Stage 2.h5
...
originalimageseries_0999_Probabilities Stage 2.h5

that I got from the autocontext workflow

What I did was write the following in a text file, save it as a .bat file. Open a windows terminal, navigate to the directory where the ilastik executable is C:\Program Files\ilastik-1.3.3post3 and drag and drop the .bat file in the terminal window. Notice that I run three similar for loops. It´s a hack because I had never scripted the windows terminal, but I wanted a quick fix and it worked. 

```
for /l %%x in (0, 1, 9) do (
.\ilastik.exe --headless --project="C:\pathtoproject\multicutboundaryproject.ilp" --raw_data="C:\pathtorawdata\originalimageseries_000%%x.tif" --probabilities="C:\pathtoprobabilities\originalimageseries_000%%x_Probabilities Stage 2.h5" --export_source="Multicut Segmentation" --output_filename_format="C:\pathtoresults\{nickname}_results.h5"
)

for /l %%x in (10, 1, 99) do (
.\ilastik.exe --headless --project="C:\pathtoproject\multicutboundaryproject.ilp" --raw_data="C:\pathtorawdata\originalimageseries_00%%x.tif" --probabilities="C:\pathtoprobabilities\originalimageseries_00%%x_Probabilities Stage 2.h5" --export_source="Multicut Segmentation" --output_filename_format="C:\pathtoresults\{nickname}_results.h5"
)

for /l %%x in (100, 1,999) do (
.\ilastik.exe --headless --project="C:\pathtoproject\multicutboundaryproject.ilp" --raw_data="C:\pathtorawdata\originalimageseries_0%%x.tif" --probabilities="C:\pathtoprobabilities\originalimageseries_0%%x_Probabilities Stage 2.h5" --export_source="Multicut Segmentation" --output_filename_format="C:\pathtoresults\{nickname}_results.h5"
)
```

**Comment by k-dominik** [comment]
Thanks for sharing this @jerolon!

@SeforaC, could you confirm that this solves your issue for you as well?

It still stands that we need to investigate this further. The error message is far from useful.
