### ISSUE TITLE
Bluetooth API required for Ilastik 1.40b8 ? 

### ISSUE THREAD

**Issue by ofrag** [ilastik/ilastik#2346]
Hi,

I'm trying to run Ilastik 1.4.0b8 on Windows WS with Windows 8.1 and get an error message saying that:
"This Windows  version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586)"

Before moving on to upgrading the OS I wanted to ask : Is bluetooth really a requirement for Ilastik to run ? 
This does not happen to me with version 1.4.0b7 

Thanks
Ofra

**Comment by k-dominik** [comment]
Hi @ofrag,

this issue is related to the latest upgrade of Qt. Unfortunately we cannot support windows 8.1 with this version anymore. Bluetooth is of course not required, nor used, but it is never the less imported at some point. With some internal refactoring on our side we might be able to restore compatibility again. We weren't sure if anyone is actually still on this windows version, but this seems to be the case.

I have found reports that suggest that removing `C:\Program Files\ilastik-1.4.0b8\Library\bin\Qt5Bluetooth.dll` might do the trick. No guarantees though (don't have a system to test that on)

Interestingly ilastik still opens fine on Windows 7. I don't have a windows 8.1 machine to test on...

Would be interesting to know if removing the file helps.

Cheers
Dominik

**Comment by ofrag** [comment]
Thanks Dominik,

Indeed removing   Qt5Bluetooth_conda.dll   did the job and Ilastik 1.4.0b8 opens and seems to work properly.
I completely understand if you stop supporting Windows 8. Probably time to switch OS on this computer. 

Thanks
Ofra

**Comment by k-dominik** [comment]
closing, as we do not support win8 anymore
