### ISSUE TITLE
Trouble running pixel classifier on SLURM

### ISSUE THREAD

**Issue by SA-uToronto** [ilastik/ilastik#2427]
Hi, I am still pretty new to SLURM and I am trying to run a ilastik pixel classifier on my HPC network. However, I keep running into errors I don't understand. I have included here a word-file with my input and error pasted.  I started out with a simple request for my job as I want the output images for my probability maps from my pixel classifiers. For now my .ilp file and my raw images are from the same folder as the run_ilastik.sh file. Hope someone can help. Thank you.

----------------------------------------------------------------------------------------
  
[ilastik_error.docx](https://github.com/ilastik/ilastik/files/6454740/ilastik_error.docx)

**Comment by k-dominik** [comment]
Hi @SA-uToronto,

your input looks good. ilastik is starting up normally, but is killed by the OS when loading the project file. How much RAM did you allocate for the job?

Cheers
Dominik

**Comment by SA-uToronto** [comment]
I didn't. I am running it on my organization's HPC system. How would i do that on a cluster and do you recommend I use GPU as I have at least 8000 images to process for a single batch.

Thank you.

Regards,
Shamini A

**Comment by SA-uToronto** [comment]
Dear Dominik,

I did not specify a memory qty for this. What memory would you suggest for running on an HPC cluster? Will that be different if I ran it on my Mac? And is GPU preferred?

Thank you for your advice.

Regards,
Shamini A

**Comment by k-dominik** [comment]
Hey @k-dominik,

ilastik currently does not use the GPU, so there's no need for one in batch mode.
How much RAM you give to ilastik can make some computations more efficient. It also depends on the number of threads you let ilastik use. As a rule of thumb, the more threads, the more RAM is needed as well.

Could you check, before running the command, how much memory you have available?

e.g. by typing the [free command](https://man7.org/linux/man-pages/man1/free.1.html) to the console:

```bash
$ free -h

# example output:

              total        used        free      shared  buff/cache   available
Mem:          7,7Gi       2,0Gi       3,1Gi       415Mi       2,6Gi       5,0Gi
Swap:         8,0Gi       1,9Gi       6,1Gi
```

**Comment by SA-uToronto** [comment]
Dear @k-dominik ,

I believe I managed to fix the memory issue. However, I think I am not uploading my files in the right format. I generated a pixel classifier using some images and am trying to process 570 images through the classier. Below is my code. 

Code
--------------------

./run_ilastik.sh --headless \
                   --project=/cluster/projects/pughlab/projects/ShaminiGBM/scImaging/Ilastik_scripts/G837_Ilastik.ilp \
                   --raw_data="/full_directory_path/*.tiff" 
                   --output_axis_order=cyx \
                   --export_source="Probabilities" \
                   --output_format="tiff sequence" \
                   --output_filename_format=/full_folder_name/{nickname}_{result_type}_{slice_index}.tiff
               
       --------------------


Except that I keep getting the following errors.
-------------
ilastik.applets.dataSelection.opDataSelection.UnsuitedAxistagsException: Axistags ['y', 'x', 'c'] don't fit data shape (570, 944, 1266, 3)
-------------

I have 570 images in my folder.
 I believe its uploading all 570 images and saving it as a 4-dimensional matrix. Is there a way to go around this or do I need to save my images as a hdf5 dataset?


Thank you so much for bearing with my basic questions..

Regards,
Shamini A

**Comment by k-dominik** [comment]
Hello @SA-uToronto,

> I believe its uploading all 570 images and saving it as a 4-dimensional matrix. Is there a way to go around this or do I need to save my images as a hdf5 dataset?


your observation is accurate.

Running stuff in batch is always a bit finicky, especially since our command line interface is not the most user-friendly. I take it you have found [our docs on that](https://www.ilastik.org/documentation/basics/headless.html) already.

there is a subtlety with the sell and how it is interpreting strings, depending on whether they are quoted (like `"myquotedstring"`) or not (`myunquotedstring`).

By specifying the `--raw_data="/somepath/*.tif"` with the quotation marks, the shell will not expand the `*` in your filename, but pass the string as is to ilastik. And there we check if there is a `*` character and then try to stack the data in one dataset.

So in principle this should be solved by removing the quotation marks around your path for raw_data (be aware that if you have spaces there or other special characters, then you need to escape them, e.g. `"/my path with spaces"` would become `/my\ path\ without\ spaces`...

Side note: ilastik will process only one file at a time this way. If you have access to a cluster you could potentially upscale that quite a bit, by starting multiple slurm jobs (even a single one for each file).

Cheers
Dominik

**Comment by SA-uToronto** [comment]
@k-dominik . It finally worked for me. It does take a long time though so I am going to follow your advice and split it into smaller batches to when I process my images on the cluster (I have about 8000+ images). 
So instead of --raw_data=file_path/*.tiff, I simply stated the /full_folder_path/*.tiff. Closing this with many thanks. Cheers.
