### ISSUE TITLE
I don't know how to read the errors.

### ISSUE THREAD

**Issue by tama34** [ilastik/ilastik#2445]
## Describe the bug
In order to proceed with machine learning, we need to know the value of OOB error.
But I don't know how to read the OOB error, so please tell me.
Where can I find OOB errors?

**Comment by k-dominik** [comment]
Hey @tama34,

you can see the oob in the log file when training. How to find the log file is a bit tricky, as it depends on the version of ilastik you use and the operating system. If you could provide me this information, I'm happy  to point you to the file.

See also [Point 8 in our FAQ](https://www.ilastik.org/documentation/basics/common_problems#8-how-can-i-know-if-the-classifier-is-doing-well)


Cheers
Dominik

**Comment by tama34** [comment]
Thanks for the reply, Dominic.
I am using version 1.3.3.
Please tell me where the log file is located.

**Comment by k-dominik** [comment]
Hello @tama34,

in ilastik versions prior to 1.4.0b8 (so 1.3.3, too), you can find the log in your home folder. The file is called `ilastik_log.txt`.

Depending on your operating system it will be in

* win: `C:\Users\<USERNAME>\ilastik_log.txt`
* osx: `/Users/<USERNAME>/ilastik_log.txt`
* linux: `/home/<USERNAME>/ilastik_log.txt`

I'd recommend to delete it (it can grow quite big), open ilastik, and train the pixel classifier in order to see the oobs there.

**Comment by tama34** [comment]
Thanks for the reply, Dominic.
I can  see the value of OOB error.
Thank you for the instruction!

**Comment by k-dominik** [comment]
awsome, closing this issue :)
