### ISSUE TITLE
What is "#0" and "overall"?

### ISSUE THREAD

**Issue by tama34** [ilastik/ilastik#2453]
## Describe the bug
I browsed variable importance table to know which features were well classified. 
There were several items in the table. 
I understood that Gini is a decrease in Gini impurity, but I can't understand the other items. 
I would like to know what they mean and how they differ from the Gini impurity decrease.

**Comment by k-dominik** [comment]
Hi @tama34,

I assume you have changed the classifier in order to look at the variable importance table. Are you doing this in order to select a smaller set of features or pure interest? In any case, you should know that these generic features in ilastik are highly correlated. As a consequence, the measurements you get in the feature importance table have little to no meaning. If your goal is a smaller feature set, the there is the [suggest features](https://www.ilastik.org/documentation/pixelclassification/pixelclassification#suggest) functionality!

Back to the original question. The `class #n`, `overall` are permutation importances. The one for the respective classes, only look at samples/labels from that class. (so #0 corresponds to the labels for the first label...). Think changing a single feature value for a sample and checking if it still predicts correctly.  I guess the idea there is that the _important_ features cannot be randomly changed.

**Comment by tama34** [comment]
Thanks for the reply, dominik.

I wanted to know which features were contributing more to the classification, so I changed the classifier. 
By removing features that were not needed, I thought I could speed up the classification process and increase accuracy.

Considering the content of your reply, if I don't consider speed and only focus on accuracy, should I select all features (37 features)?

**Comment by k-dominik** [comment]
> Considering the content of your reply, if I don't consider speed and only focus on accuracy, should I select all features (37 features)?

yes, that's what I would suggest!

**Comment by tama34** [comment]
Thank you for your answer.
