### ISSUE TITLE
multicut feature selection do-over

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2546]
This one is close to my heart - I'd say that the feature selection in multicut is my least favorite dialog and I'd really like to improve it:

![image](https://user-images.githubusercontent.com/24434157/154231111-576ad0bc-1d53-42b5-9e06-6d140f126318.png)
<sub>Okay this might be an unusual case, 3 channels for raw, 3 channels for boundaries, but still. Usually you get at least three of those columns.</sub>

We've _talked_ about this in the team already, but I'd like to gather more opinions (looking at you @constantinpape).

My current plan would be:

1) Remove the probability channels from this dialog -> use (combine) boundary channel from the seeded watershed (so there would always be a single column).
2) Do we need to allow computing features on raw data? If so, should we still hide this per default?
3) Reduce the features that can be chosen. I know that it is probably possible to construct a use-case for any combination if one really wants to, but I'd like to cover something like 90% of the use cases with a reduced set of features. Which ones would these be? All _standard_ ones on the _edges_, or even less than these?

The result could look something like this:
![image](https://user-images.githubusercontent.com/24434157/154233727-7705eb1e-8b03-4c45-9353-851a71c35ad6.png)

again, input highly appreciated!

Note: the changes proposed above would be breaking (removing probability channels, connecting the boundary channel from watershed instead).

**Comment by constantinpape** [comment]
> This one is close to my heart - I'd say that the feature selection in multicut is my least favorite dialog and I'd really like to improve it:

I completely agree with this sentiment ;).

> 1. Remove the probability channels from this dialog -> use (combine) boundary channel from the seeded watershed (so there would always be a single column).

I am not quite sure what you mean by this. Do you mean that you would always use the input to the watershed as the boundary channel? I think that would be fine.
 
> * Do we need to allow computing features on raw data? If so, should we still hide this per default?

Region features computed on raw data are pretty important and boundary features can also help; I would keep these selectable by default.

> 3\. Reduce the features that can be chosen. I know that it is probably possible to construct a use-case for any combination if one really wants to, but I'd like to cover something like 90% of the use cases with a reduced set of features. Which ones would these be? All _standard_ ones on the _edges_, or even less than these?

Absolutely. I don't even know what "edge region" features are and the granularity for everything else is way too high. Why would a user care if `kurtosis` is included in the general features or not....

My suggestion for the standard menu would be the following (think of the table as a menu mock up ;))

|Features | Boundary Map | Raw Data |
| ---------- | :----------------------: | :------------:  |
| Edge    | x                            | -                 |
| Region | -                            | x                 |

where `Edge` corresponds to everything in `Standard (Edge)` and `Region` to everything in `standard (sp)`.

**Comment by akreshuk** [comment]
I agree with Constantin's proposal and I would rename "Region" to "Superpixel" in this already awesomely optimized table.

**Comment by constantinpape** [comment]
> I agree with Constantin's proposal and I would rename "Region" to "Superpixel" in this already awesomely optimized table.

Good point, that's more obvious to users in this context.

**Comment by stuarteberg** [comment]
Simplifying that window is a great idea.  Currently, it exhibits the classic anti-pattern of a UI that too closely reflects the design of the underlying code, rather than the user's needs.

In case it helps, here a few notes:

>Remove the probability channels from this dialog

Perhaps this is a good idea to serve the 90% of use-cases as stated above.  But just to motivate the original design: If a user has more than two probability classes (i.e. more than just boundary and background), wouldn't they want them to be used as features?  Otherwise, why bother loading them in the first place?

For instance, maybe your boundary classifier can't tell the difference between cell membranes and nuclear membranes, but you'd like the nucleus to be merged into the rest of the cell.  If you have a separate channel for the nucleus interior, that would probably help the edge classifier disregard the boundaries beteen nucleus and cytoplasm, at least in theory.  On the other hand, you might hope that your original boundary probabilities could have been trained to erase that type of edge, e.g. via AutoContext.

I'm not saying whether or not such use-cases are common enough to justify the added UI complexity to support non-boundary channels.  (FWIW, the added complexity of the code is not much, as far as I can recall.)

>I don't even know what "edge region" features are

Sorry for the terrible name.  Perhaps "edge geometry" would be better.  They are the [features which solely describe the geometry of the edge][1].  They are calculated from the edge coordinate positions alone, ignoring the pixel intensities.  That highlights another flaw in the current UI: The "edge region" features will be identical, regardless of the channel you selected them for!  There is never a reason to select those features in more than one column.

[1]: http://stuarteberg.github.io/ilastikrag/accumulators.html#ilastikrag.accumulators.edgeregion.EdgeRegionEdgeAccumulator

With the 90% goal in mind, I'd say you should -- at most -- keep only the ones that are rotation-invariant (area, volume, radii).  Most users should NOT use the others, which describe the orientation of the edge.  Even the volume and radii are probably not so useful.  Even the "area" feature is admittedly related to `standard_edge_count`, i.e. the size of the edge (in voxels).  So maybe you could just discard the "edge region" features altogether.  (However, count is less invariant to the orientation of the edge, once you consider the difference between euclidean distance and chessboard distance.)

**Comment by constantinpape** [comment]
Thanks for raising the point about the additional probability maps @stuarteberg, I think if we have a very simple menu as in https://github.com/ilastik/ilastik/issues/2546#issuecomment-1041303746 we could add all probability maps, given that we only have 2 check-boxes per pmap. I agree with your point that it does not make much sense to allow providing additional probability maps without making any use of them.

> Sorry for the terrible name. Perhaps "edge geometry" would be better.

Ah, I see. I would not show these features in the default menu at all. I did a lot of benchmarking of this way back in my master thesis and they almost always have a negligible effect.

**Comment by k-dominik** [comment]
Okay awesome, the discussion is really helpful!My next iteration for the _default_ view would look something like this:

![mc_features_3](https://user-images.githubusercontent.com/24434157/155003791-49513201-2731-4619-9b98-628ecffac154.png)

where "boundary" in edge features would refer to whatever was selected as boundary channel(s) in the thresholding applet, which of course could often be redundant. UI-wise one could probably grey-out to the right of boundary, what is included in this summation. I would've hoped to remove other channels for boundary completely (so ideally only a single column for edge features), but after @stuarteberg comments it sounds like it would remove too much flexibility.
Would the present features be a good default choice to show?

**Comment by constantinpape** [comment]
A few comments from my side: 
- I assume that "boundary" and "prob-0" are actually different, i.e. that you are not repeating the probability input that is used as boundary channel
- I would add "boundary" to "Superpixel Features" as well; this can be surprisingly helpful for "unclean" predictions, e.g. from ilastik pixel classification or network predictions with noise artifacts
- the "count" feature is not dependent on the input channel, so it would make sense to only have it once for "Edge Features" and "Superpixel Features" and not duplicate it for all the channels.
- "region axes" and "region radii" for the "Superpixel Features" can probably be helpful so I would maybe not remove them. They are independent of the input, same as "count".

**Comment by akreshuk** [comment]
Indeed, I would only add prob-1, prob-2, etc if they are different from boundary. I believe this will be a fairly rare case and most users won't see it, so it won't be too confusing. For other features, I'm not sure when I would not select all. Or, when would you select skewness and not kurtosis? Does "count" alone make any sense?

**Comment by constantinpape** [comment]
> For other features, I'm not sure when I would not select all. Or, when would you select skewness and not kurtosis? Does "count" alone make any sense?

I agree with this, but somehow @k-dominik seemed to be resistant to that suggestion earlier.

**Comment by k-dominik** [comment]
We're not giving up on this :). @akreshuk discussed this again, and this seems to be what we converged on - this will be the default dialog users see - they will always be able to go to the advanced dialog.

Note: per default the users will compute the intensity features on all channels in raw data, and only in the boundary channel (whatever was selected in watershed - could be a sum of channels).

Available features:

* shape: translates to a subset of edgeregion(edge): count (area/length), radii
* Intensity: mean, Q10, Q90. For raw data always computed on _all_ channels.

Per default this would mean (in 3D) 4 shape features + (3 * n_channels_raw + 3 ) intensity features.

![MC-feature-selection](https://user-images.githubusercontent.com/24434157/184376852-89a35d90-63ab-40d5-870c-1a9824367093.png)

@akreshuk, would you say this summarizes our discussion accurately? @stuarteberg, @constantinpape do you have any opinions?

**Comment by stuarteberg** [comment]
Based on the discussion above, it sounds like you can just discard the "edge region" features, which eliminates the "shape" checkbox...
