### ISSUE TITLE
Object Classfication Batch Process Export

### ISSUE THREAD

**Issue by JiayueLiuBMI** [ilastik/ilastik#2586]
## Describe the bug
After object classification training, I ran into batch processing. But I didn't see any files or outputs in the same exporting directory when I exported the object information.

## Expected behavior
See the exported file after batch processing in the same folder directory for "object information export".

## Screenshots
If applicable, please add screenshots to help explain your problem.

## Desktop (please complete the following information):
 - ilastik version: [e.g. 1.3.2b1]
 - OS: [macOS 10.12: ]

**Comment by k-dominik** [comment]
Heya @PerfectJackie,

sorry to see that you have problems with ilastik in batch processing.

A common pitfall in batch processing is in the export settings. Could you please confirm that you still have _some_ values in curly braces e.g.`{nickname}` given for the filename in the export settings? So my guess would be if you used at least something like `/path/to/my/results/{nickname}_{result_type}.tif` (well or instead of `.tif` the format you want to export to, and of course give a proper path - if you want to have the results in the same folder as the original images, you could also use the default `{dataset_dir}/{nickname}_{result_type}.h5`...

Ref from [our docs](https://www.ilastik.org/documentation/basics/export):

> Output File Info: Use these controls to select an output file format and location. A few “magic” placeholders can be used in these settings. These are useful when you are exporting multiple datasets:

>    {dataset_dir} - the directory containing the original raw dataset
    {nickname} - the ilastik nickname of the raw dataset (usually the input file name for single file datasets and a combination of input file names for stacks)
    {result_type} - the selected ilastik result source
    {roi} - The region-of-interest as specified in the “Cutout Subregion” settings.
    {x_start}, {x_stop}, {y_start}, {y_stop}, etc - Specific axis start/stop boundaries for the region-of-interest
    {slice_index} - The index of each slice in an exported image sequence (required for all image sequence formats, not allowed with any other format).

**Comment by k-dominik** [comment]
Yes! These brackets need to be included (sorry, I forgot to reply earlier).

**Comment by k-dominik** [comment]
Hey @JiayueLiuBMI,

I hope you got it working now. I'm closing this issue for now, as there is nothing actionable on our side left. If you still have this or a similar problem, please open a new issue, or if it's purely related to usage of ilastik, consider posting on https://forum.image.sc

Cheers
Dominik
