### ISSUE TITLE
Carving, object names of only numbers error out

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2626]
## Describe the bug
When saving an object and giving it only a numerical name, some error will be raised (probably we expect it to be in the form of \w+ \d? or something like that).
Naming an object with a single number should also work (so - empty prefix).
Prefix could also change during the course of the processing.

At least two objects need to be saved.

Error appears when clicking on `Browse objects`

## Expected behavior
Single digit object names should work (or otherwise not be possible to save)

## To Reproduce
Within the Carving workflow
1. Add some  in the data selection applet
2. Do appropriate preprocessing
3. In the labeling applet, carve something out, and save it e.g. as `1`
4. Carve something different and save it with _any_ name
5. Click on `Browse objects` --> 💥 

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2022-10-24 09:45:37,027 excepthooks 19396 8593368576 Unhandled exception in thread: 'MainThread'
ERROR 2022-10-24 09:45:37,028 excepthooks 19396 8593368576 Traceback (most recent call last):
  File "/.../ilastik-1.4.0rc6-OSX.app/Contents/Resources/lib/python3.7/site-packages/ilastik/workflows/carving/carvingGui.py", line 359, in onShowObjectNames
    dialog.objectNames.addItems(sorted(names, key=_humansort_key))
TypeError: '<' not supported between instances of 'int' and 'str'
```

## Screenshots

<img width="431" alt="image" src="https://user-images.githubusercontent.com/24434157/197474236-45b3a815-1933-4890-bb51-fae438510e68.png">

## Desktop (please complete the following information):
 - ilastik version: `1.4.0rc6`
 - OS: all

**Comment by btbest** [comment]
Using only digits as object names actually works. It breaks once you mix purely-digit names with names containing string bits.

This is due to a custom sorting key we have here, which splits strings and converts digit-only chunks into integer values. So to be specific, the sorting of object names will work as long as all object names follow the same pattern of digits-vs-letters ordering. E.g. objects named "1", "1a1", "2b2a", "3c3c" will be handled just fine, as long as you don't add a name that starts with a non-digit.
