### ISSUE TITLE
Developer cannot be verified

### ISSUE THREAD

**Issue by meredithefay** [ilastik/ilastik#2638]
## Describe the bug
ilastik version 1.4.0rc6 for Mac cannot be opened "because the developer cannot be verified." After downloading the .tar.bz2, unzipping the file, and trying to open the software, I receive the attached error. There is no way to bypass the error.

## Expected behavior
I believe the software should have opened.

## To Reproduce
1. Download 64-bit Mac OS for most recent version of Ilastik. Note that Monterrey users have been instructed to download most recent version, link clicked directed to ilastik-1.4.0rc6-OSX.
2. Click on downloaded .tar.bz2 file. Archive utility expands file. .app file is contained within the tar file.
3. Click on .app, receive error.

## Error message/traceback/screenshots
![ilastik-error](https://user-images.githubusercontent.com/52324374/204634088-a9d7ddf8-3eed-4280-b579-552fd1876b17.png)

## Desktop (please complete the following information):
 - ilastik version: 1.4.0rc6-OSX
 - OS: macOS Monterey version 12.5.1

**Comment by k-dominik** [comment]
Dear @meredithefay,

thank you for contacting us. What you are seeing is sadly common with open source projects. In order to avoid this one would have to acquire a certificate and sign the app (haven't looked into this recently).

There is, however, a common workaround to still open the app, as outlined [here on apple support](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac).

This basically entails Option+Click on the app and choosing open!

**Comment by meredithefay** [comment]
Thanks so much for pointing me to a solution!
