### ISSUE TITLE
Pixel + Object Classification workflow: Export Pixel Probabilities doesn't export probabilities? 

### ISSUE THREAD

**Issue by alexlenail** [ilastik/ilastik#2739]
If you make a pixel classification workflow, and go to export pixel probabilities, it works as expected, but if you try to export pixel probabilities from the Pixel + Object classification workflow, it exports some sort of thresholded probabilities -- I'm not actually sure. But I'm sure that for the exact same image, and the exact same labels (imported), the Pixel Classification vs. the Pixel + Object Classification "Pixel Probabilities" Export produce markedly different results.

**Comment by k-dominik** [comment]
Hi @alexlenail,

I tried to reproduce this on our side but for me the two exports are (almost) identical. (Almost, as the random forest will, even with exactly the same input data, train slightly differently, because of randomness)

Did you maybe change the [export settings](https://www.ilastik.org/documentation/basics/export#settings) for any of the projects? Especially like renormalization, datatype conversions?

**Comment by alexlenail** [comment]
I don't believe I did, but I'm using pixel classification and object classification workflows independently now, so less of an issue.

**Comment by k-dominik** [comment]
Okay thank you for following up, @alexlenail! Please don't hesitate to get back to use with any new issues you should encounter!
