### ISSUE TITLE
Why is object feature selection applet needed?

### ISSUE THREAD

**Issue by martinsch** [ilastik/ilastik#869]
For a couple of weeks, object feature computation has become lazy (in that they are only computed on demand). So, why do we still need this applet? Couldn't we provide all features and let the user select them in the object classification applet (where we provide this dialog anyway)?

**Comment by akreshuk** [comment]
Because in feature computation the expensive part is the sweep over the data and looking at every pixel. So one should encourage the users to select as many features as possible in the object feature selection and then sub-set those for classification to see what works better. Also, many users want to just export object features without any classification.
